### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by behinger** [s-ccs/summerschool_simtech_2023#6]
- [x] link to jupyter notebooks @behinger 
- [x] check links @behinger 
- [x] Send MyStatsPackage to Github and to Benjamin
- [x] @bene check that all docs exist
- [x] Bene, add documentation exercise
- [x] Bene, add AlgebraOfGraphics exercise
----
- [x]  add OhMyRepl.jl to Julia installation @behinger 
- [x] write email to participants @Oesting 
- [x] Cheatsheets on a dedicated site
    - [x] best julia ones @behinger
    - [x] best GIT ones @uekerman 
    - [x] best Github action ones @uekerman 
- [x] generate the Projectswork link (@behinger)
- [x] Ask again what SimTech pays (@Oesting )
----
- [x] Add social page => @Oesting asks for github handle for SocialTeam
- [x] new landing page - daily overview? no idea @behinger
    - [x]  link to uni page
    - [x] explains briefly what this page does
- [x] add juliaInstall page @behinger
- [x] add VSCode Tips @behinger
- [x] Remove speakers @behinger 
- [x] add logo ;-) @behinger
- [x] replace schedule with https://www.simtech.uni-stuttgart.de/img/events/Summer-School/Flyer_Programm_langes_Format_2308010.png @behinger
- [x] FirstSteps => LinearAlgebra.jl @behinger
- [x] add R column in cheatsheet @Oesting
- [x] Project Work? @Oesting 
- [x] write email (Friday) ManagementTeam @Oesting 
- [x] Write email Social Team @Oesting 
- [x] write email speaker @behinger

**Comment by uekerman** [comment]
Technical writing slides from SSE: https://github.com/Simulation-Software-Engineering/Lecture-Material/blob/main/04_documentation/technical_writing_slides.md

**Comment by behinger** [comment]
@uekerman still 2 todos for you, the cheatsheets. maybe just link some?
